### ISSUE TITLE
MAV_tools not working 

### ISSUE THREAD

**Issue by ahm23ad** [CCNYRoboticsLab/mav_tools#1]
after compiling the mav tool successfully  i can't get to run the ctrl interface node or city flyer 

and there are some missing files such as quad_simple _planner ! and no single line to communicate  the information from the ctrl interface to the board HL or LL

**Comment by idryanov** [comment]
Could you post the output exactly?

**Comment by ahm23ad** [comment]
i am sorry i am not at the lab right now  in Sunday i will post the post the output for you .

just want to ask dose the 2d planner obstacle avoidance in mav_tools  work on asctec pelican now or not ?

thanks

**Comment by idryanov** [comment]
We've used it on our Asctec quadrotor for obstacle avoidance. It's still in an experimental stage though.

**Comment by ahm23ad** [comment]
did you use the same code here that in your gitub or another version ?? the things is i want to on your latest work so i can  help upgrading the work to new level we are new but my team form from the best student ever

**Comment by idryanov** [comment]
On 08/31/2012 01:35 PM, ahm23ad wrote:

> the things is i want to on your latest work so i can help upgrading

Github has the latest version. Keep in mind that this code is for the 
asctec firmware form before 2012. We are currently in the process of 
upgrading it for the newly-released asctec LL firmware

**Comment by ahm23ad** [comment]
aha on the autopilot program i got V2 for ll or hl so is that before 2012 or not 

on Sunday me and my team will begin running the ctrl interface node and see the effeteness of the obstacle and planning algorithms that has been implemented .

i hope in future we can give back for this repo and of course use your experience in some issues

**Comment by idryanov** [comment]
On 08/31/2012 01:58 PM, ahm23ad wrote:

> aha on the autopilot program i got V2 for ll or hl so is that before
> 2012 or not
> 
> on Sunday me and my team will begin running the ctrl interface node and
> see the effeteness of the obstacle and planning algorithms that has been
> implemented .
> 
> i hope in future we can give back for this repo and of course use your
> experience in some issues
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccny-ros-pkg/mav_tools/issues/1#issuecomment-8200089.

You probably have the new LL firmware. We are currently upgrading out 
system to use that, we should have it in the next week or so, and I'll 
put up a wiki page for it.

**Comment by ahm23ad** [comment]
aha that is great i hope better documentation for packages such as ctrl interface because util now i can't figure how ctrl node send velocity commands or some packages as simple planner dosen't exist but it's in the mainfest.xml so better 
clarification will be great 

thanks
