### ISSUE TITLE
laser high estimation  

### ISSUE THREAD

**Issue by ahm23ad** [CCNYRoboticsLab/mav_tools#2]
is required to have the mirror thing for the laser high estimation so that 2d planner or  ctrl interface works ??

**Comment by ccny-ros-pkg** [comment]
You need some type of height estimation for stable flight. This can come from a sonar, a vision system, or a laser scanner. In our system, we use a laser scanner, together with a mirror to deflect the rays. If you use a laser scanner with a mirror, you can take a look at the laser_height_estimation package

**Comment by ahm23ad** [comment]
but if i want just to drive in 2d world  and for experiment only is it oky to operate your city flyer codes  without the mirrors  ??

by the way i got asctec pelican quad with hykuo 30L

**Comment by ahm23ad** [comment]
let rephrase my question can i do it using your code here "ctrl node" especially without the deflective mirrors but i will get some draft or it won't work at all and it will crash down ??

**Comment by idryanov** [comment]
On 01-Sep-12 15:09, ahm23ad wrote:

> let rephrase my question can i do it using your code here "ctrl node"
> especially without the deflective mirrors but i will get some draft or
> it won't work at all and it will crash down ??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccny-ros-pkg/mav_tools/issues/2#issuecomment-8215644.

You can use the code without any kind of height estimation, but You will 
have to control the thrust manually, using a remote control.
