### ISSUE TITLE
TF unavailable 

### ISSUE THREAD

**Issue by ahm23ad** [CCNYRoboticsLab/mav_tools#6]
TF unavailable from base link to odom   that the error i got when i start the flyer interface

**Comment by idryanov** [comment]
You need to be running something which publishes odometry, for example,
laser scan matcher

**Comment by ahm23ad** [comment]
i did that but not working for me :( always saying not available  from laser base link to Tf and the tree of tf  on RVIZ show alway that the tree isn't connect
